\documentclass{beamer} % class of presentation document
\usepackage{Sweave} % sweave package
\usepackage{beamerthemebars} % creates the pretty bars and links

\begin{document}

\title{Joint Bayesian estimatation of diets from Stable Isotopes and Fatty Acid compositions}
\author{Phil}

\frame{\titlepage} % create title page

\section{Estimating diet proportions}


\begin{frame}

You are what you eat. Almost. Take Stable Isotope $i$ of a predator preying on $j=1...J$ prey species:

\[
  SI_{i}=\sum_{j} p_j SI_{i,j}
\]

This would be true if stable isotopes for all preys were incorporated 1:1, but some isotopes are preferentially assimilated. Furthermore, different diet items have different amounts of each element (i.e., N in protein). This leads to:

\[
  SI_{i}=\sum_{j} p_j (SI_{i,j} + \delta_{i,j} + \beta_{i,j} SI_{i,j})
\]

\end{frame}

\begin{frame}

This is essentially a regression model, and we can estiamte parameters $\beta_{i,j}$ and $\delta_{i,j}$ from controlled experiments in which $p_j$ is known...which lets us estiamte $p_j$ in a diet study as the only unknown.\\

\quad

Unfortunatelly, Fatty Acids are more complicated, as they are measured as percentages, or more precisely, a composition. These have funny properties: the most obvious one is that they have a sum constraint: 

\[
  \sum_f FA_f = 1
\]


\end{frame}

\begin{frame}

In the theory of 'you are what you eat', this means that:

\[
  FA_{f}=C(\sum_{j} p_j FA_{f,j})
\]

where C is a closure operation enforcing the sum to one constraint.\\

\end{frame}

\begin{frame}

Again, it is not all that simple since different prey species do not have the same fat content $(\phi)$ to start with, such that eating a kg of one is not the same as eating a kg of another. \\

\quad

Also, FAs are differentally assimilated, and some are metabolised to some extent, resulting in only a relative proportion $\Delta_{f,j}$, where again $\sum_f \Delta_{f,j} = 1$. This leads to 

\[
  FA_{f}=C(\sum_{j} p_j [FA_{f,j} \Delta_{f,j} \phi_{j}])
\]

\end{frame}

% this section will show the intialization code

\begin{frame}

Again, $\Delta_{f,j}$ can be estiamted from controlled experiments (it's a bit more tricky here because of the compositional nature...), and $\phi_{j}$ can be emasured along with fatty acid profiles, or can be found in literature.\\
\quad

The session today follows two tutorials:
\begin{itemize}
\item a simulated example (in the vignettes folder) showing how Bayesian methods can be used to estiamte $p$
\item an analysis of experimental data from a 2006 squid diet paper (Stowasser et al.), which first estiamtes the deltas for both markers from single diet treatments and then estiamtes diet proportions for animals in a mixed food treatment. 

\end{itemize}

Both will make up the demonstration of the method in the final paper...

\end{frame}

\end{document}